#!/bin/bash

docker run -it --rm \
    -p 8888:8888 \
    -v $(pwd)/kernels:/home/dbuser/.local/share/jupyter/kernels/ \
    -v $HOME/.ssh/:/home/dbuser/.ssh \
    -v $HOME/.databrickscfg:/home/dbuser/.databrickscfg \
    -v $(pwd):/home/dbuser/notebooks \
    bwalter42/databrickslabs_jupyterlab:2.2.0-rc4 \
    /opt/conda/bin/jupyter $@